# Generated by Django 6.0.2 on 2026-03-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="features",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="status",
            field=models.CharField(
                choices=[("AC", "Active"), ("IN", "Inactive")], default="IN"
            ),
        ),
        migrations.AlterField(
            model_name="globalfeatureflag",
            name="status",
            field=models.CharField(
                choices=[("AC", "Active"), ("IN", "Inactive")], default="IN"
            ),
        ),
    ]
