# Generated by Django 6.0.2 on 2026-03-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_features_description_alter_featureflag_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="user_id",
            field=models.IntegerField(default=-1),
        ),
    ]
